# Generated by Django 2.1.7 on 2019-02-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=120)),
                ('trailtext', models.CharField(max_length=120)),
                ('thumbnail', models.URLField()),
                ('url', models.URLField()),
            ],
        ),
    ]
